openapi: 3.1.0
info:
  title: Notification schemas
  version: ''
  description: >
    Use [Application
    notifications](/docs/product/applications/application-notifications/overview)
    and [loyalty
    notifications](/docs/product/loyalty-programs/loyalty-notifications/overview)
    to notify the system of your choice of certain changes that happened in
    Talon.One.

    **Note:** Required fields are not omitted if they are empty (have `null`
    value).
servers:
  - url: https://yourbaseurl.talon.one
security: []
tags:
  - name: Campaign notifications
    description: >
      Represents the
      [notifications](/docs/product/applications/application-notifications/overview)

      about campaign-related changes.


      **Note:** The value of the `NotificationType` property indicates the
      campaign change:

      - `CampaignNotification` signifies one of the following events:
        - [Campaign created](#tag/Campaign-notifications/operation/campaignCreatedNotification)
        - [Campaign state changed](#tag/Campaign-notifications/operation/campaignStateChangedNotification)
        - [Campaign rules changed](#tag/Campaign-notifications/operation/campaignRulesetChangedNotification)
        - [Campaign edited](#tag/Campaign-notifications/operation/campaignEditedNotification)
        - [Campaign collection edited](#tag/Campaign-notifications/operation/campaignCollectionEditedNotification)
        - [Campaign deleted](#tag/Campaign-notifications/operation/campaignDeletedNotification)
      - `CampaignEvaluationTreeChanged` signifies [Campaign evaluation tree
      changed](#tag/Campaign-notifications/operation/campaignEvaluationTreeChangedNotification).
  - name: Coupon notifications
    description: >
      Represents the
      [notifications](/docs/product/applications/application-notifications/overview)

      about coupons.
  - name: Loyalty card notifications
    description: >-
      Represents the
      [notifications](/docs/product/loyalty-programs/loyalty-notifications/overview)
      about changes to loyalty points in card-based loyalty programs.
  - name: Loyalty notifications
    description: >
      Represents the
      [notifications](/docs/product/loyalty-programs/loyalty-notifications/overview)

      about changes to loyalty points in profile-based loyalty programs.
  - name: Strikethrough pricing notifications
    description: >
      Represents the
      [notifications](/docs/product/applications/application-notifications/overview)

      about strikethrough pricing updates.
paths: {}
webhooks:
  campaignCreatedNotification:
    $ref: webhooks/campaignCreatedNotification.yaml
  campaignStateChangedNotification:
    $ref: webhooks/campaignStateChangedNotification.yaml
  campaignRulesetChangedNotification:
    $ref: webhooks/campaignRulesetChangedNotification.yaml
  campaignEditedNotification:
    $ref: webhooks/campaignEditedNotification.yaml
  campaignCollectionEditedNotification:
    $ref: webhooks/campaignCollectionEditedNotification.yaml
  campaignDeletedNotification:
    $ref: webhooks/campaignDeletedNotification.yaml
  campaignEvaluationTreeChangedNotification:
    $ref: webhooks/campaignEvaluationTreeChangedNotification.yaml
  strikethroughLabelingNotification:
    $ref: webhooks/strikethroughLabelingNotification.yaml
  createCouponData:
    $ref: webhooks/createCouponData.yaml
  couponsData:
    $ref: webhooks/couponsData.yaml
  asyncCouponsData:
    $ref: webhooks/asyncCouponsData.yaml
  updateCouponsData:
    $ref: webhooks/updateCouponsData.yaml
  deleteCouponsData:
    $ref: webhooks/deleteCouponsData.yaml
  expiringPointsNotification:
    $ref: webhooks/expiringPointsNotification.yaml
  expiringCardPointsNotification:
    $ref: webhooks/expiringCardPointsNotification.yaml
  addedDeductedPointsNotification:
    $ref: webhooks/addedDeductedPointsNotification.yaml
  addedDeductedPointsBalancesNotification:
    $ref: webhooks/addedDeductedPointsBalancesNotification.yaml
  pendingActivePointsNotification:
    $ref: webhooks/pendingActivePointsNotification.yaml
  tierUpgradeNotification:
    $ref: webhooks/tierUpgradeNotification.yaml
  tierDowngradeNotification:
    $ref: webhooks/tierDowngradeNotification.yaml
  tierWillDowngradeNotification:
    $ref: webhooks/tierWillDowngradeNotification.yaml
  expiringCouponsNotification:
    $ref: webhooks/expiringCouponsNotification.yaml
  cardAddedDeductedPointsNotification:
    $ref: webhooks/cardAddedDeductedPointsNotification.yaml
  cardAddedDeductedPointsBalancesNotification:
    $ref: webhooks/cardAddedDeductedPointsBalancesNotification.yaml
components:
  securitySchemes: {}
